default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafioeasy_back_development
  username: valdersonjr
  password: sorvete123
  host: localhost
  port: 5432

test:
  <<: *default
  database: desafioeasy_back_test
  username: valdersonjr
  password: sorvete123
  host: localhost
  port: 5432

production:
  <<: *default
  database: easy_desafio
  username: easy_desafio_user
  password: <%= ENV["EASY_DESAFIO_BACKEND_DATABASE_PASSWORD"] %>
  host: dpg-cpk3utqcn0vc73b0501g-a
  port: 5432
